### ISSUE TITLE
Exceptions in after() block swallowed, but still fail the suite

### ISSUE THREAD

**Issue by ptomato** [pipobscure/demitasse#8]
I haven't verified whether this still occurs in 2.x, but in 1.x any exceptions thrown in an after() block (and presumably also before(), afterEach(), beforeEach()) would not be printed anywhere, but the exit code would still be nonzero. This would make debugging difficult since it wasn't clear why the suite was failing and where the failure occurred.

**Comment by pipobscure** [comment]
This is fixed in v2 already and there are tests for it.
